services:
  - type: web
    name: tiranga-colour-trading
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.hooqiccbtakpcogziona:tiranga-db123@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
